### ISSUE TITLE
Commenti soluzioni territoriali 2018

### ISSUE THREAD

**Issue by tunonnaemiliana** [lucach/wiki-olinfo#1]
E' possibile inserire dei commenti nella soluzione di "escursione" ? L'algoritmo scritto e' decisamente criptico :(

**Comment by lucach** [comment]
In effetti quelle soluzioni sono state scritte un po' frettolosamente.
Condividendo la tua osservazione, ho aggiunto qualche idea generale e qualche commento al codice. Prova a darci un'occhiata e dimmi se va meglio ;)

**Comment by tunonnaemiliana** [comment]
Grazie multiple[xer]
